<?php
    $jobCollection = $this->getLoadedJobCollection();
    $iterator = 1;
    $total = $jobCollection->count();
    $firstPager = true;

/**
    - https://www.maximehuran.fr/les-sessions-et-magento-2/
    - Récupérer / modifier une session depuis un template
    - $this->getJobSession()->setNumberByPage(10);
    - $this->getJobSession()->getNumberByPage();
*/
?>
 
<div class="job-wrapper">
    <div class="job-pager">
        <?php echo __('View per page : '); ?>
        <?php foreach($this->getAvailablePager() AS $numberByPage): ?>
            <?php if(!$firstPager) echo ' - '; ?>
            <a href="<?php echo $this->getPagerUrl($numberByPage); ?>"><?php echo $numberByPage; ?></a>
            <?php $firstPager = false; ?>
        <?php endforeach; ?>
    </div>
    <ol class="jobs list">
<?php foreach($jobCollection AS $job): ?>
    <li class="item<?php echo ($iterator == 1) ? ' first' : ''; ?><?php echo ($total == $iterator) ? ' last' : ''; ?>">
        <div class="title">
            <a href="<?php echo $this->getJobUrl($job); ?>" title="<?php echo $job->getTitle(); ?>">
                <?php echo $job->getTitle(); ?>
            </a>
        </div>
        <div class="department_name">
            <?php echo __('Department : '); ?>
            <a href="<?php echo $this->getDepartmentUrl($job); ?>" title="<?php echo $job->getDepartmentName(); ?>">
                <?php echo $job->getDepartmentName(); ?>
            </a>
        </div>
        <div class="type"><?php echo $job->getType(); ?></div>
        <div class="location"><?php echo $job->getLocation(); ?></div>
        <div class="date"><?php echo $this->formatDate($job->getDate()); ?></div>
        <div class="description"><?php echo $job->getDescription(); ?></div>
    </li>
    <?php $iterator++; ?>
<?php endforeach; ?>
    </ol>
</div>